# Development environment override
services:
  api:
    volumes:
      - ./api:/app
      - /app/var
      - ./api/docker/frankenphp/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./api/docker/frankenphp/conf.d/app.dev.ini:/usr/local/etc/php/conf.d/app.dev.ini:ro
      # If you develop on Mac or Windows you can remove the vendor/ directory
      #  from the bind-mount for better performance by enabling the next line:
      # - /app/vendor
    environment:
      MERCURE_EXTRA_DIRECTIVES: demo
      # See https://xdebug.org/docs/all_settings#mode 
      XDEBUG_MODE: "${XDEBUG_MODE:-debug}"
      XDEBUG_CONFIG: >-
        client_host=host.docker.internal
        idekey=VSCODE
    extra_hosts:
      # Ensure that host.docker.internal is correctly defined on Linux
      - host.docker.internal:host-gateway
    tty: true
    platform: linux/amd64

  async:
    volumes:
      - ./api:/app
      - /app/var
      - ./api/docker/frankenphp/conf.d/app.dev.ini:/usr/local/etc/php/conf.d/app.dev.ini:ro
      # If you develop on Mac or Windows you can remove the vendor/ directory
      #  from the bind-mount for better performance by enabling the next line:
      - /app/vendor
    platform: linux/amd64
  
  scheduler:
    volumes:
      - ./api:/app
      - /app/var
      - ./api/docker/frankenphp/conf.d/app.dev.ini:/usr/local/etc/php/conf.d/app.dev.ini:ro
      # If you develop on Mac or Windows you can remove the vendor/ directory
      #  from the bind-mount for better performance by enabling the next line:
      - /app/vendor
    platform: linux/amd64