api_platform:
    title: KYC PHC API 
    version: 1.0.0
    formats:
        jsonld: ['application/ld+json']
        json: ['application/json']
        csv:    ['text/csv']
        xlsx:   ['application/vnd.openxmlformats-officedocument.spreadsheetml.sheet']
    docs_formats:
        jsonld: ['application/ld+json']
        jsonopenapi: ['application/vnd.openapi+json']
        html: ['text/html']
    collection:
        pagination:
            enabled_parameter_name: pagination
            items_per_page_parameter_name: itemsPerPage
    defaults:
        pagination_client_enabled: true
        pagination_client_items_per_page: true
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
        extra_properties:
            standard_put: true
            rfc_7807_compliant_errors: true
    keep_legacy_inflector: false
    use_symfony_listeners: true
